worker_processes 1; 

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    gzip on;


    server {

        listen 80;
        server_name localhost;

        client_max_body_size 3M;

        root /var/www/html/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php-fpm:9000;
            fastcgi_index index.php;
             fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            try_files $fastcgi_script_name =404;
        }

        location /Uploads/ {
            alias /var/www/html/Uploads/;
            autoindex off;
            access_log off;
            expires max;
        }
        
        location ~ /\. {
            deny all;
        }

        location /admin/ {
           alias /var/www/html/admin/;
            index index.php;

            try_files $uri $uri/ /admin/index.php$query_string;

            location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php-fpm:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            try_files $fastcgi_script_name =404;
        }
            
            location ~ /\. {
                deny all;
            }
        }
    }
}